/**
 * Mock Action Definitions seed data.
 * Covers all 5 capability types and multiple categories.
 * These are the reusable building blocks that appear in the canvas Node Library.
 */

import type { ActionDefinition } from '@/interfaces';

export const MOCK_ACTIONS: ActionDefinition[] = [
    // ── Triggers ──
    {
        id: 'act-trg-01',
        actionKey: 'trigger.schedule',
        name: 'Schedule Trigger',
        description: 'Starts the workflow on a defined cron schedule.',
        category: 'Triggers',
        capability: 'api',
        scope: 'global',
        icon: '⏱️',
        defaultNodeTitle: 'Scheduled Run',
        createdAt: '2026-03-01T10:00:00Z',
        updatedAt: '2026-03-01T09:00:00Z',
    },

    // ── Connectors ──
    {
        id: 'act-cnn-01',
        actionKey: 'connector.emr',
        name: 'Epic EMR Connector',
        description: 'Bidirectional sync with the facility EMR.',
        category: 'Connectors',
        capability: 'api',
        scope: 'client',
        icon: '🏥',
        defaultNodeTitle: 'Epic Binding',
        createdAt: '2026-03-01T10:00:00Z',
        updatedAt: '2026-03-01T09:00:00Z',
    },

    // ── Ends ──
    {
        id: 'act-end-01',
        actionKey: 'end.success',
        name: 'Success Flow',
        description: 'Marks the workflow completion as successful.',
        category: 'Ends',
        capability: 'rules',
        scope: 'global',
        icon: '✅',
        defaultNodeTitle: 'Success',
        createdAt: '2026-03-01T10:00:00Z',
        updatedAt: '2026-03-01T09:00:00Z',
    },
    {
        id: 'act-end-02',
        actionKey: 'end.error',
        name: 'Error Flow',
        description: 'Marks the workflow completion as an error state.',
        category: 'Ends',
        capability: 'rules',
        scope: 'global',
        icon: '🚨',
        defaultNodeTitle: 'Error',
        createdAt: '2026-03-01T10:00:00Z',
        updatedAt: '2026-03-01T09:00:00Z',
    },

    // ── API Capability ──
    {
        id: 'act-001',
        actionKey: 'api.eligibility.verify',
        name: 'Verify Eligibility',
        description: 'Calls the payer eligibility API (270/271) to verify patient insurance coverage and benefits.',
        category: 'Eligibility',
        capability: 'api',
        scope: 'global',
        icon: '🔍',
        defaultNodeTitle: 'Verify Eligibility',
        createdAt: '2026-01-05T10:00:00Z',
        updatedAt: '2026-02-15T09:00:00Z',
    },
    {
        id: 'act-002',
        actionKey: 'api.claim.submit',
        name: 'Submit Claim',
        description: 'Submits a claim to the clearinghouse for payer adjudication via the 837 transaction set.',
        category: 'Documents',
        capability: 'api',
        scope: 'global',
        icon: '📤',
        defaultNodeTitle: 'Submit Claim',
        createdAt: '2026-01-08T14:00:00Z',
        updatedAt: '2026-02-10T11:30:00Z',
    },
    {
        id: 'act-003',
        actionKey: 'api.pm.update',
        name: 'Update Practice Management',
        description: 'Updates claim status, notes, or follow-up dates in the connected practice management system.',
        category: 'Documents',
        capability: 'api',
        scope: 'global',
        icon: '📋',
        defaultNodeTitle: 'Update PM System',
        createdAt: '2026-01-10T09:00:00Z',
        updatedAt: '2026-02-20T16:00:00Z',
    },
    {
        id: 'act-004',
        actionKey: 'api.claim.status',
        name: 'Check Claim Status',
        description: 'Queries the clearinghouse or payer for real-time claim adjudication status (277 transaction).',
        category: 'Eligibility',
        capability: 'api',
        scope: 'global',
        icon: '📊',
        defaultNodeTitle: 'Check Claim Status',
        createdAt: '2026-01-12T11:00:00Z',
        updatedAt: '2026-02-18T13:45:00Z',
    },

    // ── AI Capability ──
    {
        id: 'act-005',
        actionKey: 'ai.denial.classify',
        name: 'AI Classify Denial',
        description: 'Uses an LLM to classify a denial into category/subcategory and recommend the optimal resolution path.',
        category: 'Denials',
        capability: 'ai',
        scope: 'global',
        icon: '🤖',
        defaultNodeTitle: 'Classify Denial',
        createdAt: '2026-01-15T09:00:00Z',
        updatedAt: '2026-02-28T14:00:00Z',
    },
    {
        id: 'act-006',
        actionKey: 'ai.appeal.draft',
        name: 'AI Draft Appeal Letter',
        description: 'Generates a customized appeal letter based on denial reason, clinical documentation, and payer templates.',
        category: 'Denials',
        capability: 'ai',
        scope: 'global',
        icon: '✍️',
        defaultNodeTitle: 'Draft Appeal',
        createdAt: '2026-01-20T10:30:00Z',
        updatedAt: '2026-02-25T15:20:00Z',
    },
    {
        id: 'act-007',
        actionKey: 'ai.document.classify',
        name: 'AI Classify Document',
        description: 'Classifies an incoming document (fax, scan, attachment) by type for routing to the correct department.',
        category: 'Documents',
        capability: 'ai',
        scope: 'global',
        icon: '📄',
        defaultNodeTitle: 'Classify Document',
        createdAt: '2026-01-25T08:00:00Z',
        updatedAt: '2026-02-22T12:00:00Z',
    },
    {
        id: 'act-008',
        actionKey: 'ai.coding.audit',
        name: 'AI Coding Audit',
        description: 'Analyzes CPT/ICD codes against clinical documentation to flag potential coding discrepancies.',
        category: 'Coding',
        capability: 'ai',
        scope: 'global',
        icon: '🔬',
        defaultNodeTitle: 'Audit Codes',
        createdAt: '2026-02-01T09:30:00Z',
        updatedAt: '2026-02-27T11:00:00Z',
    },

    // ── RPA Capability ──
    {
        id: 'act-009',
        actionKey: 'rpa.portal.login',
        name: 'RPA Payer Portal Login',
        description: 'Automates login to a payer web portal using stored credentials for claim status retrieval or auth submission.',
        category: 'Auth',
        capability: 'rpa',
        scope: 'client',
        icon: '🖥️',
        defaultNodeTitle: 'Portal Login',
        createdAt: '2026-02-05T14:00:00Z',
        updatedAt: '2026-02-26T10:30:00Z',
    },
    {
        id: 'act-010',
        actionKey: 'rpa.portal.status',
        name: 'RPA Claim Status Scrape',
        description: 'Scrapes claim status from payer portal after login, extracting adjudication details.',
        category: 'Denials',
        capability: 'rpa',
        scope: 'client',
        icon: '🔄',
        defaultNodeTitle: 'Scrape Status',
        createdAt: '2026-02-08T11:00:00Z',
        updatedAt: '2026-02-24T09:00:00Z',
    },

    // ── Human Capability ──
    {
        id: 'act-011',
        actionKey: 'human.review.triage',
        name: 'Human Triage Review',
        description: 'Creates a task in the human work queue for manual triage review when AI confidence is below threshold.',
        category: 'Human Tasks',
        capability: 'human',
        scope: 'global',
        icon: '👤',
        defaultNodeTitle: 'Human Review',
        createdAt: '2026-01-18T10:00:00Z',
        updatedAt: '2026-02-20T14:30:00Z',
    },
    {
        id: 'act-012',
        actionKey: 'human.review.appeal',
        name: 'Human Appeal Review',
        description: 'Routes a drafted appeal letter to a specialist for review and approval before submission to the payer.',
        category: 'Human Tasks',
        capability: 'human',
        scope: 'global',
        icon: '✅',
        defaultNodeTitle: 'Review Appeal',
        createdAt: '2026-01-22T13:00:00Z',
        updatedAt: '2026-02-19T16:00:00Z',
    },

    // ── Rules Capability ──
    {
        id: 'act-013',
        actionKey: 'rules.timely.check',
        name: 'Timely Filing Check',
        description: 'Evaluates the claim against payer-specific timely filing deadlines and flags at-risk claims.',
        category: 'Denials',
        capability: 'rules',
        scope: 'global',
        icon: '⏰',
        defaultNodeTitle: 'Check Timely Filing',
        createdAt: '2026-02-01T09:00:00Z',
        updatedAt: '2026-02-23T11:45:00Z',
    },
    {
        id: 'act-014',
        actionKey: 'rules.route.payer',
        name: 'Payer Routing Rules',
        description: 'Applies payer-specific routing rules to determine the appropriate resolution path for a denied claim.',
        category: 'Denials',
        capability: 'rules',
        scope: 'client',
        icon: '🔀',
        defaultNodeTitle: 'Apply Payer Rules',
        createdAt: '2026-02-05T10:30:00Z',
        updatedAt: '2026-02-21T14:00:00Z',
    },

    // ── Messaging ──
    {
        id: 'act-015',
        actionKey: 'api.sms.send',
        name: 'Send SMS Notification',
        description: 'Sends an SMS message to a patient or staff member via the configured messaging provider.',
        category: 'Messaging',
        capability: 'api',
        scope: 'global',
        icon: '💬',
        defaultNodeTitle: 'Send SMS',
        createdAt: '2026-01-28T09:00:00Z',
        updatedAt: '2026-02-17T10:00:00Z',
    },
    {
        id: 'act-016',
        actionKey: 'api.fax.send',
        name: 'Send Fax',
        description: 'Sends a fax document to a recipient via the configured fax gateway.',
        category: 'Messaging',
        capability: 'api',
        scope: 'global',
        icon: '📠',
        defaultNodeTitle: 'Send Fax',
        createdAt: '2026-02-03T11:00:00Z',
        updatedAt: '2026-02-16T15:30:00Z',
    },
];
