/**
 * Mock Skills seed data.
 * Covers a realistic spread of statuses, categories, clients, and environments.
 */

import type { Skill } from '@/interfaces';

export const MOCK_SKILLS: Skill[] = [
    {
        id: 'sk-001',
        name: 'Denial Triage & Resolution',
        skillKey: 'DENTRI',
        description: 'Classifies incoming denials using AI, routes to the appropriate resolution path based on denial category and payer rules.',
        categoryId: 1,
        category: 'Denials',
        clientId: '1',
        payerId: 'payer-uhc',
        owner: 'AR Team Lead',
        tags: ['denial', 'triage', 'ai-classify'],
        status: 'published',
        environment: 'prod',
        createdAt: '2026-01-15T09:30:00Z',
        updatedAt: '2026-02-28T14:22:00Z',
        updatedBy: 'AR Team Lead',
    },
    {
        id: 'sk-002',
        name: 'Eligibility Verification',
        skillKey: 'ELIGVR',
        description: 'Performs real-time eligibility checks against payer portals before claim submission to reduce preventable denials.',
        categoryId: 1,
        category: 'Eligibility',
        clientId: '1',
        payerId: 'payer-aetna',
        owner: 'Billing Manager',
        tags: ['eligibility', 'pre-check', 'payer-portal'],
        status: 'published',
        environment: 'prod',
        createdAt: '2026-01-10T11:00:00Z',
        updatedAt: '2026-02-20T10:05:00Z',
        updatedBy: 'Billing Manager',
    },
    {
        id: 'sk-003',
        name: 'Prior Authorization Follow-up',
        skillKey: 'PRAUTH',
        description: 'Automates prior auth status checks and escalation workflows when approval is pending beyond threshold days.',
        categoryId: 1,
        category: 'Auth',
        clientId: '1',
        payerId: 'payer-cigna',
        owner: 'Auth Coordinator',
        tags: ['prior-auth', 'follow-up', 'escalation'],
        status: 'draft',
        environment: 'dev',
        createdAt: '2026-02-18T08:45:00Z',
        updatedAt: '2026-03-01T16:30:00Z',
        updatedBy: 'Auth Coordinator',
    },
    {
        id: 'sk-004',
        name: 'Payment Posting Reconciliation',
        skillKey: 'PAYREC',
        description: 'Matches ERA/EOB payments against expected amounts, flags variances, and creates adjustment tasks for underpayments.',
        categoryId: 1,
        category: 'Payments',
        clientId: 'client-summit',
        owner: 'Cash Posting Lead',
        tags: ['payment', 'reconciliation', 'era'],
        status: 'published',
        environment: 'prod',
        createdAt: '2026-01-22T13:15:00Z',
        updatedAt: '2026-02-15T09:45:00Z',
        updatedBy: 'Cash Posting Lead',
    },
    {
        id: 'sk-005',
        name: 'Claim Scrubbing Pre-Submit',
        skillKey: 'CLMSCR',
        description: 'Validates claims against coding rules and payer-specific requirements before submission to reduce clean claim rejections.',
        categoryId: 1,
        category: 'Coding',
        clientId: '1',
        payerId: 'payer-bcbs',
        owner: 'Coding Supervisor',
        tags: ['claim-scrub', 'coding', 'pre-submit'],
        status: 'draft',
        environment: 'staging',
        createdAt: '2026-02-25T10:00:00Z',
        updatedAt: '2026-03-02T11:20:00Z',
        updatedBy: 'Coding Supervisor',
    },
    {
        id: 'sk-006',
        name: 'Patient Statement Generation',
        skillKey: 'PTSTMT',
        description: 'Generates patient responsibility statements after insurance adjudication, including payment plan options.',
        categoryId: 1,
        category: 'Documents',
        clientId: 'client-summit',
        owner: 'Patient Accounts',
        tags: ['patient', 'statement', 'billing'],
        status: 'draft',
        environment: 'prod',
        createdAt: '2025-11-05T14:00:00Z',
        updatedAt: '2026-01-30T08:00:00Z',
        updatedBy: 'Patient Accounts',
    },
    {
        id: 'sk-007',
        name: 'Appeal Letter Drafting',
        skillKey: 'APPLET',
        description: 'Uses AI to draft appeal letters based on denial reason code, clinical documentation, and payer-specific appeal templates.',
        categoryId: 1,
        category: 'Denials',
        clientId: '1',
        payerId: 'payer-uhc',
        owner: 'AR Team Lead',
        tags: ['appeal', 'ai-draft', 'denial'],
        status: 'draft',
        environment: 'dev',
        createdAt: '2026-02-28T15:30:00Z',
        updatedAt: '2026-03-03T09:10:00Z',
        updatedBy: 'AR Team Lead',
    },
    {
        id: 'sk-008',
        name: 'Timely Filing Alert',
        skillKey: 'TMFLAG',
        description: 'Monitors claims approaching the payer timely filing deadline and triggers escalation tasks for at-risk claims.',
        categoryId: 1,
        category: 'Denials',
        clientId: 'client-summit',
        payerId: 'payer-aetna',
        owner: 'Billing Manager',
        tags: ['timely-filing', 'alert', 'deadline'],
        status: 'published',
        environment: 'prod',
        createdAt: '2026-01-08T10:30:00Z',
        updatedAt: '2026-02-12T14:55:00Z',
        updatedBy: 'Billing Manager',
    },
    {
        id: 'sk-009',
        name: 'Secondary Payer Billing',
        skillKey: 'SECPAY',
        description: 'Routes claims to secondary insurance after primary adjudication, applying coordination of benefits rules.',
        categoryId: 1,
        category: 'Eligibility',
        clientId: '1',
        owner: 'Billing Manager',
        tags: ['secondary', 'cob', 'payer'],
        status: 'draft',
        environment: 'dev',
        createdAt: '2026-03-01T08:00:00Z',
        updatedAt: '2026-03-03T17:00:00Z',
        updatedBy: 'Billing Manager',
    },
    {
        id: 'sk-010',
        name: 'Coding Audit Workflow',
        skillKey: 'CODAUD',
        description: 'AI-assisted coding audit that flags potential upcoding/downcoding issues and routes to human review.',
        categoryId: 1,
        category: 'Coding',
        clientId: 'client-summit',
        owner: 'Compliance Officer',
        tags: ['coding-audit', 'compliance', 'ai'],
        status: 'published',
        environment: 'staging',
        createdAt: '2026-02-10T09:00:00Z',
        updatedAt: '2026-02-27T13:40:00Z',
        updatedBy: 'Compliance Officer',
    },
    {
        id: 'sk-011',
        name: 'Fax Intake Processing',
        skillKey: 'FAXINP',
        description: 'Receives inbound faxes, classifies document type using AI, and routes to appropriate department queue.',
        categoryId: 1,
        category: 'Documents',
        clientId: '1',
        owner: 'Operations Manager',
        tags: ['fax', 'intake', 'document-classify'],
        status: 'draft',
        environment: 'prod',
        createdAt: '2025-10-20T12:00:00Z',
        updatedAt: '2026-01-15T16:30:00Z',
        updatedBy: 'Operations Manager',
    },
    {
        id: 'sk-012',
        name: 'Appointment Reminder Outreach',
        skillKey: 'APTREM',
        description: 'Sends multi-channel reminders (SMS, email) for upcoming appointments to reduce no-show rates.',
        categoryId: 1,
        category: 'Messaging',
        clientId: 'client-summit',
        owner: 'Front Desk Lead',
        tags: ['appointment', 'reminder', 'sms'],
        status: 'published',
        environment: 'prod',
        createdAt: '2026-01-05T10:00:00Z',
        updatedAt: '2026-02-18T11:15:00Z',
        updatedBy: 'Front Desk Lead',
    },
    {
        id: 'sk-013',
        name: 'RPA Payer Portal Status Check',
        skillKey: 'RPACHK',
        description: 'Uses RPA bots to log into payer portals and retrieve claim status updates for batch reconciliation.',
        categoryId: 1,
        category: 'RPA',
        clientId: '1',
        payerId: 'payer-bcbs',
        owner: 'AR Team Lead',
        tags: ['rpa', 'payer-portal', 'status-check'],
        status: 'draft',
        environment: 'staging',
        createdAt: '2026-02-20T14:00:00Z',
        updatedAt: '2026-03-02T16:45:00Z',
        updatedBy: 'AR Team Lead',
    },
    {
        id: 'sk-014',
        name: 'Charge Capture Review',
        skillKey: 'CHGCAP',
        description: 'Reviews charge capture entries against clinical documentation to ensure completeness before billing.',
        categoryId: 1,
        category: 'Coding',
        clientId: 'client-summit',
        owner: 'Coding Supervisor',
        tags: ['charge-capture', 'review', 'coding'],
        status: 'published',
        environment: 'prod',
        createdAt: '2026-01-28T09:30:00Z',
        updatedAt: '2026-02-25T10:10:00Z',
        updatedBy: 'Coding Supervisor',
    },
    {
        id: 'sk-015',
        name: 'Patient Balance Follow-up',
        skillKey: 'PTBAL',
        description: 'Automated patient balance follow-up workflow with escalating communication cadence.',
        categoryId: 1,
        category: 'Messaging',
        clientId: '1',
        owner: 'Patient Accounts',
        tags: ['patient-balance', 'follow-up', 'collections'],
        status: 'draft',
        environment: 'prod',
        createdAt: '2025-09-12T11:00:00Z',
        updatedAt: '2026-01-10T09:00:00Z',
        updatedBy: 'Patient Accounts',
    },
];
